apiVersion: v1
kind: Service
metadata:
  name: napi
  labels:
    app: napi
spec:
  type: NodePort
  selector:
    app: napi
  ports:
    - name: http
      protocol: TCP
      port: 80           # port w klastrze
      targetPort: 3000   # port w kontenerze
      nodePort: 31212    # port na hoście (zewnętrzny)
