apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtopsky
  namespace: dtopsky    # <-- tu
  labels:
    app: dtopsky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtopsky
  template:
    metadata:
      labels:
        app: dtopsky
    spec:
      containers:
        - name: dtopsky
          image: harbor.zatto-lab.cloud/d-topsky/d-topsky:0.0.36
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: dtopsky-secrets
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dtopsky-secrets
                  key: SECRET_KEY
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: dtopsky-secrets
                  key: ALLOWED_HOSTS
            - name: DEBUG
              value: "False"
