apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtopsky
  labels:
    app: dtopsky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtopsky
  template:
    metadata:
      labels:
        app: dtopsky
    spec:
      containers:
        envFrom:
        - secretRef:
            name: dtopsky-secrets
        - name: dtopsky
          image: harbor.zatto-lab.cloud/d-topsky/d-topsky:0.0.20
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "dtopsky.topsky.app" 
